---
- name: Enable Ansible repos for RHEL equal or lower then version 8.5
  community.general.rhsm_repository:
    name: ansible-2-for-rhel-8-x86_64-rpms
    state: enabled
  when:
    - ansible_facts['distribution'] == "RedHat"
    - (ansible_facts['distribution_version'] == "8.0") or
      (ansible_facts['distribution_version'] == "8.1") or
      (ansible_facts['distribution_version'] == "8.2") or
      (ansible_facts['distribution_version'] == "8.3") or
      (ansible_facts['distribution_version'] == "8.4") or
      (ansible_facts['distribution_version'] == "8.5")

- name: Disable Ansible repos for RHEL equal or above version 8.6
  community.general.rhsm_repository:
    name: ansible-2-for-rhel-8-x86_64-rpms
    state: disabled
  when:
    - ansible_facts['distribution'] == "RedHat"
    - (ansible_facts['distribution_version'] == "8.6") or
      (ansible_facts['distribution_version'] == "8.7") or
      (ansible_facts['distribution_version'] == "8.8")

- name: Installation of Ansible packages for RHEL equal or lower then version 8.5
  ansible.builtin.dnf:
    name:
      - ansible
    disablerepo: epel
    state: present
  when:
    - ansible_facts['os_family'] == "RedHat"
    - (ansible_facts['distribution_version'] == "8.0") or
      (ansible_facts['distribution_version'] == "8.1") or
      (ansible_facts['distribution_version'] == "8.2") or
      (ansible_facts['distribution_version'] == "8.3") or
      (ansible_facts['distribution_version'] == "8.4") or
      (ansible_facts['distribution_version'] == "8.5")

- name: Remove legacy Ansible packages for RHEL equal or above version 8.6
  ansible.builtin.dnf:
    name:
      - ansible
    state: absent
  when:
    - ansible_facts['os_family'] == "RedHat"
    - (ansible_facts['distribution_version'] == "8.6") or
      (ansible_facts['distribution_version'] == "8.7") or
      (ansible_facts['distribution_version'] == "8.8") or
      (ansible_facts['distribution_major_version']|int >= 9)

- name: Installation of Ansible packages for RHEL equal or above version 8.6
  ansible.builtin.dnf:
    name:
      - ansible-core
    state: present
  when:
    - ansible_facts['os_family'] == "RedHat"
    - (ansible_facts['distribution_version'] == "8.6") or
      (ansible_facts['distribution_version'] == "8.7") or
      (ansible_facts['distribution_version'] == "8.8") or
      (ansible_facts['distribution_major_version']|int >= 9)
