---
- name: Install insights-client with malware detection
  ansible.builtin.dnf:
    name:
      - insights-client
      - yara
    state: present
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version']|int >= 8

- name: Ensure core_collect is enabled in insights-client.conf
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/insights-client/insights-client.conf
    insertafter: "^#core_collect=True"
    line: "core_collect=True"
  when: not ansible_check_mode
