---
- name: Install insights-client
  ansible.builtin.dnf:
    name:
      - insights-client
    state: present
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version']|int >= 8

- name: Install malware detection
  ansible.builtin.dnf:
    name:
      - yara
    state: present
  when:
    - ansible_facts['distribution'] == "RedHat"
    - (ansible_facts['distribution_version'] == "8.7") or
      (ansible_facts['distribution_version'] == "8.8") or
      (ansible_facts['distribution_version'] == "8.9") or
      (ansible_facts['distribution_version'] == "8.10") or
      (ansible_facts['distribution_major_version']|int >= 9)

- name: Ensure core_collect is enabled in insights-client.conf
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/insights-client/insights-client.conf
    insertafter: "^#core_collect=True"
    line: "core_collect=True"

- name: Check if /etc/insights-client/malware-detection-config.yml exists
  ansible.builtin.stat:
    path: /etc/insights-client/malware-detection-config.yml
  register: stat_result_yara

- name: Ensure malware scan is activated
  ansible.builtin.lineinfile:
    path: /etc/insights-client/malware-detection-config.yml
    regexp: '^test_scan: '
    line: "test_scan: false"
  when:
    - stat_result_yara.stat.exists
