---
- name: Deploy kdump packages
  ansible.builtin.dnf:
    name:
      - crash
      - kexec-tools
    state: present

- name: Enable and start kdump service
  ansible.builtin.service:
    name: kdump.service
    state: started
    enabled: true
  when:
    - ansible_facts['virtualization_type'] != "docker"
