---
- name: Restart cockpit
  ansible.builtin.service:
    name: cockpit.socket
    state: restarted
  when:
    - ansible_facts['virtualization_type'] != "docker"

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  when:
    - ansible_facts['virtualization_type'] != "docker"
